type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  active: Boolean!
  created_at: String!
  updated_at: String!
}

type Query {
  users: [User!]!
  user(id: ID!): User!
}

input UserInput {
  firstName: String!
  lastName: String!
  email: String!
  active: Boolean!
}

type Mutation {
  createUser(input: UserInput!): User!
  updateUser(id: ID!, input: UserInput!): User!
  deleteUser(id: ID!): Boolean!
}
